# Generated by Django 4.1.6 on 2023-02-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stud',
            new_name='stud1',
        ),
    ]
